spring:
  profiles:
    active: production
  application:
    name: shiki-adapter
  datasource:
    url: jdbc:postgresql://ec2-34-247-172-149.eu-west-1.compute.amazonaws.com:5432/ddetvfiudb0ivb
    username: fvcjgzhsepbshy
    password: 520959e6bd4b368e0abebfb5db928fbbc754d647a3fd2f639e2ae5c346acdf30
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/migration/changelog-master.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html

api:
  default: kodik

  kodik-api:
    url: https://kodikapi.com
    enable-feign-client: true
    token: 8dbadba6fae83b80586e4656b562e464
    blocked-regions: RU, UA, KZ
  shikimori-v1:
    url: https://shikimori.one
    enable-feign-client: true
    client-id: BVHnZI_noTQ-9qDSYkW5CEI5Vum4rGcv5pjn5NYy86M
    client-secret: HVHbiwjEB7Fij7MFn2FYa_efSEr3iwBS4ps4XPyFZhk

token:
  secret: f791e522-f5c4-41e4-a7a3-d5466edbb3c1
  expiresIn: 86400


---
spring:
  profiles: development

  datasource:
    url: jdbc:postgresql://localhost:5432/shiki-adapter
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    liquibase:
      change-log: classpath:/db/migration/changelog-master.xml
      url: ${spring.datasource.url}
      user: ${spring.datasource.username}
      password: ${spring.datasource.password}