spring:
  application:
    name: shiki-adapter
  datasource:
    url: jdbc:postgresql://localhost:5432/report-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    liquibase:
      change-log: classpath:/db/migration/changelog.xml
      url: ${spring.datasource.url}

server:
  port: 8080