spring:
  profiles:
    active: production
  application:
    name: shiki-adapter
  datasource:
    url: jdbc:postgresql://ec2-52-48-159-67.eu-west-1.compute.amazonaws.com:5432/d2gca1mf3sm2qf
    username: gmaqygqwilphrn
    password: 3678e7e27a9d914340cdeb34e0f7f371f86fd5fa2eee0205e82aa3252c3f91db
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/migration/changelog-master.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html

api:
  default: kodik

  kodik-api:
    url: https://kodikapi.com
    enable-feign-client: true
    token: 8dbadba6fae83b80586e4656b562e464
    blocked-regions: RU, UA, KZ
  shikimori-v1:
    url: https://shikimori.one
    enable-feign-client: true
    client-id: BVHnZI_noTQ-9qDSYkW5CEI5Vum4rGcv5pjn5NYy86M
    client-secret: HVHbiwjEB7Fij7MFn2FYa_efSEr3iwBS4ps4XPyFZhk



---
spring:
  profiles: development

  datasource:
    url: jdbc:postgresql://localhost:5432/shiki-adapter
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    liquibase:
      change-log: classpath:/db/migration/changelog-master.xml
      url: ${spring.datasource.url}
      user: ${spring.datasource.username}
      password: ${spring.datasource.password}